# Generated by Django 6.0.1 on 2026-02-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_user_created_at_user_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type_user",
            field=models.CharField(
                blank=True,
                choices=[("Administrador", "Administrador")],
                help_text="Type_user",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
