# Generated by Django 6.0.1 on 2026-02-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_type_user_alter_user_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="type_user",
            field=models.CharField(
                blank=True,
                choices=[("Administrador", "Administrador"), ("Default", "Default")],
                default="Default",
                help_text="Type_user",
                max_length=50,
                null=True,
            ),
        ),
    ]
