# Generated by Django 6.0.1 on 2026-02-11 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "cache_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Dados armazenados"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Criou"),
                            ("UPDATE", "Atualizou"),
                            ("DELETE", "Deletou"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Saindo"),
                            ("DOWNLOAD", "Baixou"),
                        ],
                        max_length=20,
                        verbose_name="Ação",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "dono",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regristro de Auditoria",
                "verbose_name_plural": "Registros de auditoria",
                "ordering": ["-timestamp"],
            },
        ),
    ]
