# Generated by Django 6.0.1 on 2026-02-03 11:35

import django.db.models.deletion
import uuid
import vault.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=vault.models.upload_path, verbose_name="arquivo"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome do arquivo"),
                ),
                ("file_size", models.PositiveIntegerField(verbose_name="Bytes")),
                ("types", models.CharField(max_length=50, verbose_name="Type")),
                (
                    "woner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dono",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Arquivo",),
                "verbose_name_plural": "Arquivos",
                "ordering": ["-created_at"],
            },
        ),
    ]
