# Generated by Django 6.0.1 on 2026-02-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="woner",
            new_name="owner",
        ),
    ]
