# Generated by Django 6.0.1 on 2026-02-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0002_rename_woner_file_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file_size",
            field=models.PositiveIntegerField(editable=False, verbose_name="Bytes"),
        ),
        migrations.AlterField(
            model_name="file",
            name="name",
            field=models.CharField(
                editable=False, max_length=255, verbose_name="Nome do arquivo"
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="types",
            field=models.CharField(editable=False, max_length=50, verbose_name="Type"),
        ),
    ]
