# Generated by Django 6.0.1 on 2026-02-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0003_alter_file_file_size_alter_file_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file_size",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="Bytes"
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="name",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=255,
                null=True,
                verbose_name="Nome do arquivo",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="types",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=50,
                null=True,
                verbose_name="Type",
            ),
        ),
    ]
