# Generated by Django 6.0.1 on 2026-02-10 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0005_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="vault.folder",
                verbose_name="Pasta",
            ),
        ),
    ]
