# Generated by Django 6.0.1 on 2026-02-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0006_file_folder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="file",
            new_name="arquivo",
        ),
        migrations.RenameField(
            model_name="file",
            old_name="folder",
            new_name="ficheiro",
        ),
    ]
