# Generated by Django 6.0.1 on 2026-02-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0007_rename_file_file_arquivo_rename_folder_file_ficheiro"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="arquivo",
            new_name="file",
        ),
        migrations.RenameField(
            model_name="file",
            old_name="ficheiro",
            new_name="folder",
        ),
    ]
