# Generated by Django 6.0.1 on 2026-02-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0008_rename_arquivo_file_file_rename_ficheiro_file_folder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="types",
            new_name="file_type",
        ),
    ]
