# Generated by Django 6.0.1 on 2026-02-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0009_rename_types_file_file_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="file",
            new_name="uploaded_file",
        ),
    ]
