# Generated by Django 6.0.1 on 2026-02-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0002_rename_folder_sharedlink_ficheiro"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sharedlink",
            old_name="ficheiro",
            new_name="folder",
        ),
    ]
